mylist=[]
mylist.append('apple')
mylist.append("grapes")
mylist.append("green apple")
mylist.append("mango")
mylist.append("kiwi")
mylist.append("pineapple")
mylist.append("blackcurrant")
mylist.append("watermelon")
mylist.remove('apple')
print(len(mylist))
print(mylist[3])
mylist.sort()
print(mylist)
mylist.reverse()
print(mylist)